### ISSUE TITLE
C2679 compiler error

### ISSUE THREAD

**Issue by coderc264** [JlnWntr/Lua-Adapter#3]
I've succefully compiled this wrapper in windows but i suggest to add "#include string" after "#include iostream" to avoid compile error in visual studio "C2679: binary '<<' : no operator found which takes a right-hand operand of type 'std::string' (or there is no acceptable conversion)"

Thanks in advance

**Comment by JlnWntr** [comment]
I _could_ add this, but you are more than welcome to create a pull request for that. The Lua-Adapter could use some more contributors.  Thank you so much!

**Comment by coderc264** [comment]
Sorry but, i don't know how to open a pull request.
I've created a local branch with this fix buit i'm unable to push

**Comment by JlnWntr** [comment]
You fork from this repository, edit all your changes on your fork, add, commit and push **to your fork**. Then click on the button _New Pull request_ on the [main page of the (original) Lua-Adapter](https://github.com/JlnWntr/Lua-Adapter). Does this help you? :)

**Comment by coderc264** [comment]
Done.
Thanks

**Comment by JlnWntr** [comment]
Merged. Thank you, too.
